name: CA-Bench dry run

on:
  pull_request:
  push:
    branches: [ main ]
    paths-ignore:
    paths-ignore:
      - '*.md'

jobs:
  dry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install backoff pyyaml

      - name: Orchestrator dry run
        run: |
          python orchestrator.py --config bench.yaml --dry-run

      - name: Sanity-check artifacts
        run: |
          test -f results/scores.csv
          grep -q "norm_hamming" results/scores.csv
